config/routes.rb
Rails.application.routes.draw do

  
  resources :articles, only:[:create, :new , :index] do
    resources :votes, only: [:create, :destroy]
  end
  resources :categories, only: [:show]
  resources :users, only:[:new, :create]
  root to: 'articles#index'
 
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2 }
  validates :title, length: { maximum: 30 }
  validates :text, presence: true, length: { minimum: 10 }
  belongs_to :user, class_name: 'User', foreign_key: :author_id
  has_many :votes, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :categories, through: :tags
  has_one_attached :image

  scope :top_voted, -> { order(vote_count: :desc).limit(1).first }
  scope :include_votes, -> { includes(:votes).order(created_at: :desc) }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ApplicationHelper

  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, only: %i[new create update edit]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.first
    @top_voted = Article.top_voted
  end

  # GET /articles/1
  # GET /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)
    if @article.valid? && @article.save
      if params[:category].nil?
        Tag.create(article_id: @article.id, category_id: 5)
      else
        params[:category].each do |cid|
          Tag.create(article_id: @article.id, category_id: cid)
        end
      end
      redirect_to new_article_path, notice: 'article Created Successfully'
    else
      render 'new'
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:author_id, :title, :text, :image, :vote_count)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="card text-dark bg-white container w-75 ">
<div class="card-header w-100">
<h4>Create an article</h4>
</div>
<div class="card-body">
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    
    <%= f.input :title %>
    <%= f.input :text %>
    <%= f.input :image, direct_upload: true , class:"text-muted" %>
    <div class="d-flex text-dark">
        <% priority_categories().each do |category| %>
          <div class="form-group pr-4">
            <%= label_tag "#{category.name}" %>
            <%= check_box_tag "category[]", category.id %>
          </div>
        <% end %>
    </div>
   
  </div>

  <div class="form-actions">
    <div class="btn">
    <%= f.button :submit %>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="article mb-4">
 
<div class="landing bg-dark">
    <div class="card border-0 overflow-hidden flex-wrap " style="height: 75vh;">
  
              <%= image_render top_voted_article%>
              <div class="card-img-overlay d-flex flex-column justify-content-end">
                <h5 class="card-title word-break text-truncate d-block text-capitalize landing-title text-wrap"><%= extract_title top_voted_article %></h5>
                <p class="card-text word-break text-truncate d-block text-capitalize text-white landing-text"><%= extract_text top_voted_article %></p>
              </div>
             
    </div>


</div>

<div class="categories d-flex flex-row flex-wrap">
 <%priority_categories(4).each do |category|%>
    <div class="card border-0  overflow-hidden  w-25 " style="height: 15rem;">
      <%= link_to category_path(category) do%>
               <%= image_render top_of_category category%>
                <div class="card-img-overlay d-flex flex-column ">
                <h4 class="font-weight-bolder  underline pb-2 mt-2 mb-5 mr-auto text-wrap landing-category-name border-bt "><%= category.name%></h4>
                <h5 class="mb-4  text-wrap landing-category-article mt-5 "><%= extract_title top_of_category category %></h5>
               </div>
        
      <%end%>
    </div>
  <%end%>
</div>




</div>

app/views/articles/new.html.erb
<div class="new-article p-5">

<%= render 'form', article: @article %>


</div>